"""Add Expense model

Revision ID: 0760b9f56ca2
Revises: 8953f0b0e09e
Create Date: 2025-12-16 11:12:26.628470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0760b9f56ca2'
down_revision: Union[str, Sequence[str], None] = '8953f0b0e09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('MEDICAL_SUPPLIES', 'UTILITIES', 'SALARIES', 'MAINTENANCE', 'RENT', 'OTHER', name='expensecategory'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.Column('recorder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_title'), 'expenses', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_title'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
